### ISSUE TITLE
bytes() are initialized to nil not to 0

### ISSUE THREAD

**Issue by tivvit** [aerospike/aerospike-mod-lua#4]
Hello, 

In the docs http://www.aerospike.com/docs/udf/api/bytes.html is told that

```
> local b = bytes(18)
Bytes()
> b[1]
0
```

but when I do

```
function test(rec, bin)
    local a = bytes(10)
    return a[1]
end
```

and 

```
aql> register module 'bytes_test.lua'
OK, 1 module added.

aql> execute bytes_test.test() on scan.b_test where PK = 1
+------+
| test |
+------+
|      |
+------+
1 row in set (0.000 secs)
```

I get `nil`

I looked to the code, and https://github.com/aerospike/aerospike-common/blob/master/src/main/aerospike/as_bytes.c#L33 calls wrapped calloc https://github.com/aerospike/aerospike-common/blob/9c595786295be4a9396abed37d61d65e4a89a89d/src/main/citrusleaf/cf_alloc.c#L32 which should initialize memory to 0.
But I think that when pushing memory to lua this function is used https://github.com/aerospike/aerospike-mod-lua/blob/d0fba23eef9418616eae0f3029f4b5df9f2a7c3d/src/main/mod_lua_val.c#L217 which sets values to NULL == nil in lua. But it just a suggestion, I am not sure.

**Comment by wchu-citrusleaf** [comment]
We have updated the documentation to reflect that the number is purely a capacity setting, and no initialization is done. This is more in-line with new list items which also has nil as members. Thanks.
