### ISSUE TITLE
initializing of List with table that contains nil

### ISSUE THREAD

**Issue by jarda-manana** [aerospike/aerospike-mod-lua#7]
I found this confusing, maybe mentioning it in the documentation is worth it:
```
> local l = list {1,nil,3}
List(1,3)
```

**Comment by bwhisler** [comment]
Thanks -- I agree the behavior is confusing.  We'll add a mention of it to the list and map docs.

**Comment by mcoberly2** [comment]
Updated: https://www.aerospike.com/docs/udf/api/list.html
Updated: https://www.aerospike.com/docs/udf/api/map.html
