### ISSUE TITLE
Doubts about record.bin_names and geojson.

### ISSUE THREAD

**Issue by vVv-AA** [aerospike/aerospike-mod-lua#8]
Client: Python 3.7.2
Server: 3.16

------------------------------------------------------------------------------------------------------------------------
When saving records, we have the option to mark a bin as None (in which case, the bin is not stored). Other option is to mark the bin value as aerospike.null(). The client gets back aerospike.null() as the value for the bin. This clearly distinguishes omitted bins vs null bins.
The bin is also stored in the server when using aerospike.null().

This cannot be done with a udf, since _record[bin] always results in `nil` and record.bin_names also does not return name for this bin. This is sort of inconsistent. If record.bin_names returns the bin name, we can do the above mentioned check in udf too. 

Is there any way short of passing expected bin names to udf and checking against that to solve this issue? Or, if viable this be made a feature request.

This seems to be because for these bins as_bin_inuse returns false, if I understand the code correct.
https://github.com/aerospike/aerospike-server/blob/2b99c53f71d2da4782d4c5111243b7db395ea618/as/src/base/udf_record.c#L886

------------------------------------------------------------------------------------------------------------------------

Also, does aerospike plan to expose geojson's in udf with geo query feature? 

Please let me know, if this issue does not belong in this repo and should be moved to aerospike-server repo.

**Comment by bwhisler** [comment]
We'd like to better understand these aerospike.null() bins.  Are records being written by the Python client with a bin value of aerospike.null() and stored in the database?  And then the client reads the record back and finds a bin with an aerospike.null() value in it?  This seems odd, as we'd expect that writing a bin with a null value would delete the bin.  How exactly are these records being written?  Knowing this I think we could determine why a UDF would not see the bin and perhaps make an adjustment as needed.

Regarding GeoJSON, there are currently no plans to add support for Geo queries in UDFs.

**Comment by vVv-AA** [comment]
@bwhisler Sorry for the jumping the gun here. I rechecked the code. It is working as intended. aerospike.null() is not returned. When reading the bins, there was a default value being passed in some part of the code. Missed that part. Closing the issue. Thanks.

I also, misunderstood the as_bin_inuse then. Since the null bins are not stored, what do AS_PARTICLE_TYPE_NULL and AS_BIN_STATE_UNUSED correspond to?

**Comment by bwhisler** [comment]
Both AS_PARTICLE_TYPE_NULL and AS_BIN_STATE_UNUSED are used internally to help manage a bin array as a record is being processed.  We'll typically allocate an (oversized) array of bins when processing a record, and those NULL/UNUSED constants help indicate how much of the internal bin array is actually needed to handle the record in question.
